[0m10:13:50.255025 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252A571B280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252A80FB670>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252A80FB400>]}


============================== 10:13:50.262581 | 2289a8e3-a935-4487-b4a6-3eaaf43ad5b6 ==============================
[0m10:13:50.262581 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:13:50.263941 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\HARSH\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:13:50.263941 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\HARSH\Desktop\Dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:13:50.266894 [debug] [MainThread]: Command `dbt run` failed at 10:13:50.263941 after 0.11 seconds
[0m10:13:50.266894 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252A571B280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252A80FB640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252A80FB6A0>]}
[0m10:13:50.266894 [debug] [MainThread]: Flushing usage events
[0m11:30:36.017268 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EFEA2DB1F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EFECCBF580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EFECCBF3A0>]}


============================== 11:30:36.024550 | 7104f1e2-4282-4f56-81c3-596929d7ae19 ==============================
[0m11:30:36.024550 [info ] [MainThread]: Running with dbt=1.8.6
[0m11:30:36.025737 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HARSH\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:30:36.027231 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\HARSH\Desktop\Dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:30:36.028411 [debug] [MainThread]: Command `dbt run` failed at 11:30:36.028411 after 0.12 seconds
[0m11:30:36.028938 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EFEA2DB1F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EFECCBF520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002EFECCBF610>]}
[0m11:30:36.029998 [debug] [MainThread]: Flushing usage events
