[0m10:14:57.789970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D1030B220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D12CEB460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D12CEB280>]}


============================== 10:14:57.795152 | b53983ec-ce35-47d8-9605-463accec5a46 ==============================
[0m10:14:57.795152 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:14:57.796778 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\HARSH\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\HARSH\\Desktop\\Dbt\\noora_health\\logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:14:58.054115 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'b53983ec-ce35-47d8-9605-463accec5a46', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D105D8C70>]}
[0m10:14:58.117173 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'b53983ec-ce35-47d8-9605-463accec5a46', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D12AD97B0>]}
[0m10:14:58.117173 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m10:14:58.148476 [debug] [MainThread]: checksum: 2f2fb10c73cafe3e79aa104295a8244291492b32b5598ce46af770f7d0bd5194, vars: {}, profile: , target: , version: 1.8.6
[0m10:14:58.148476 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m10:14:58.148476 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'b53983ec-ce35-47d8-9605-463accec5a46', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D1003A1A0>]}
[0m10:15:00.193950 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'b53983ec-ce35-47d8-9605-463accec5a46', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D131CF4F0>]}
[0m10:15:00.384293 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'b53983ec-ce35-47d8-9605-463accec5a46', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D12C432E0>]}
[0m10:15:00.384293 [info ] [MainThread]: Found 3 models, 4 data tests, 420 macros
[0m10:15:00.388075 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'b53983ec-ce35-47d8-9605-463accec5a46', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D12B4BB20>]}
[0m10:15:00.389417 [info ] [MainThread]: 
[0m10:15:00.389417 [debug] [MainThread]: Acquiring new postgres connection 'master'
[0m10:15:00.396059 [debug] [ThreadPool]: Acquiring new postgres connection 'list_erp_db'
[0m10:15:02.679717 [debug] [ThreadPool]: Using postgres connection "list_erp_db"
[0m10:15:02.679717 [debug] [ThreadPool]: On list_erp_db: /* {"app": "dbt", "dbt_version": "1.8.6", "profile_name": "noora_health", "target_name": "dev", "connection_name": "list_erp_db"} */

    select distinct nspname from pg_namespace
  
[0m10:15:02.679717 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m10:15:02.822141 [debug] [ThreadPool]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", SSL encryption
connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", no encryption

[0m10:15:02.916823 [debug] [ThreadPool]: Postgres adapter: Error running SQL: /* {"app": "dbt", "dbt_version": "1.8.6", "profile_name": "noora_health", "target_name": "dev", "connection_name": "list_erp_db"} */

    select distinct nspname from pg_namespace
  
[0m10:15:02.928668 [debug] [ThreadPool]: Postgres adapter: Rolling back transaction.
[0m10:15:02.929238 [debug] [ThreadPool]: Postgres adapter: Error running SQL: macro list_schemas
[0m10:15:02.929238 [debug] [ThreadPool]: Postgres adapter: Rolling back transaction.
[0m10:15:02.932563 [debug] [ThreadPool]: On list_erp_db: No close available on handle
[0m10:15:02.933579 [debug] [MainThread]: Connection 'master' was properly closed.
[0m10:15:02.936522 [debug] [MainThread]: Connection 'list_erp_db' was properly closed.
[0m10:15:02.936522 [info ] [MainThread]: 
[0m10:15:02.938714 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 2.55 seconds (2.55s).
[0m10:15:02.938714 [error] [MainThread]: Encountered an error:
Database Error
  connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", SSL encryption
  connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", no encryption
  
[0m10:15:02.944390 [debug] [MainThread]: Command `dbt run` failed at 10:15:02.944390 after 5.25 seconds
[0m10:15:02.944390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D1030B220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D133AB760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018D13434A00>]}
[0m10:15:02.944390 [debug] [MainThread]: Flushing usage events
[0m10:15:50.081888 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3784B1F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A227550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A227370>]}


============================== 10:15:50.090893 | 17735147-3aa0-4ef0-8323-7a602f57d237 ==============================
[0m10:15:50.090893 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:15:50.090893 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Users\\HARSH\\Desktop\\Dbt\\noora_health\\logs', 'profiles_dir': 'C:\\Users\\HARSH\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:15:50.266743 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '17735147-3aa0-4ef0-8323-7a602f57d237', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F38062620>]}
[0m10:15:50.326361 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '17735147-3aa0-4ef0-8323-7a602f57d237', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A222DA0>]}
[0m10:15:50.326361 [info ] [MainThread]: Registered adapter: postgres=1.8.2
[0m10:15:50.330575 [debug] [MainThread]: checksum: 2f2fb10c73cafe3e79aa104295a8244291492b32b5598ce46af770f7d0bd5194, vars: {}, profile: , target: , version: 1.8.6
[0m10:15:50.502698 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m10:15:50.502698 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m10:15:50.547067 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '17735147-3aa0-4ef0-8323-7a602f57d237', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A7D4130>]}
[0m10:15:50.704843 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '17735147-3aa0-4ef0-8323-7a602f57d237', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A7D56F0>]}
[0m10:15:50.704843 [info ] [MainThread]: Found 3 models, 4 data tests, 420 macros
[0m10:15:50.704843 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '17735147-3aa0-4ef0-8323-7a602f57d237', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A7FAAA0>]}
[0m10:15:50.704843 [info ] [MainThread]: 
[0m10:15:50.720532 [debug] [MainThread]: Acquiring new postgres connection 'master'
[0m10:15:50.720532 [debug] [ThreadPool]: Acquiring new postgres connection 'list_erp_db_public'
[0m10:15:50.803412 [debug] [ThreadPool]: Using postgres connection "list_erp_db_public"
[0m10:15:50.803412 [debug] [ThreadPool]: On list_erp_db_public: BEGIN
[0m10:15:50.803412 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m10:15:50.924929 [debug] [ThreadPool]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", SSL encryption
connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", no encryption

[0m10:15:51.019159 [debug] [ThreadPool]: Postgres adapter: Error running SQL: BEGIN
[0m10:15:51.019159 [debug] [ThreadPool]: Postgres adapter: Rolling back transaction.
[0m10:15:51.019159 [debug] [ThreadPool]: Postgres adapter: Error running SQL: macro list_relations_without_caching
[0m10:15:51.019159 [debug] [ThreadPool]: Postgres adapter: Rolling back transaction.
[0m10:15:51.019159 [debug] [ThreadPool]: On list_erp_db_public: No close available on handle
[0m10:15:51.034851 [debug] [MainThread]: Connection 'master' was properly closed.
[0m10:15:51.034851 [debug] [MainThread]: Connection 'list_erp_db_public' was properly closed.
[0m10:15:51.034851 [info ] [MainThread]: 
[0m10:15:51.034851 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.33 seconds (0.33s).
[0m10:15:51.034851 [error] [MainThread]: Encountered an error:
Database Error
  connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", SSL encryption
  connection to server at "ec2-13-232-185-70.ap-south-1.compute.amazonaws.com" (13.232.185.70), port 5432 failed: FATAL:  no pg_hba.conf entry for host "182.70.45.45", user "postgres", database "erp_db", no encryption
  
[0m10:15:51.034851 [debug] [MainThread]: Command `dbt test` failed at 10:15:51.034851 after 1.04 seconds
[0m10:15:51.034851 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3784B1F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A7FADA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013F3A76E380>]}
[0m10:15:51.034851 [debug] [MainThread]: Flushing usage events
